language: cpp

os: 
  - linux
  - osx

compiler:
  - gcc
  - clang
  
before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo add-apt-repository -y ppa:kubuntu-ppa/backports; fi 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; sudo apt-get --force-yes install icub-common; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  brew install `brew deps --1 yarp | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g'`; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  brew install cmake goocanvas  sdl sdl_gfx sdl_image gfortran; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  brew install ode --enable-double-precision; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];  brew tap homebrew/science; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew install opencv; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; brew install --with-qt3support qt; fi
  #install yarp from master
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON
  - make
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build 
  - cmake ../
  
script:

  - cmake --build .
  - sudo make install
  - sudo make uninstall
