language: cpp

compiler:
  - gcc
  - clang
  
before_script:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports 
  - sudo apt-get update
  - sudo apt-get --force-yes install icub-common
  # Build yarp master
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake ../ -DCREATE_GUIS:BOOL=ON -DCREATE_LIB_MATH:BOOL=ON -DCREATE_OPTIONAL_CARRIERS:BOOL=ON -DENABLE_yarpcar_bayer_carrier:BOOL=ON
  - make
  - sudo make install
  - cd ../..
  - mkdir build
  - cd build 
  - cmake ../
  
script:

  - cmake --build .
  - sudo make install
  - sudo make uninstall
